import type { TestCase } from '#dilatorily/advent-of-code/scripts/start/types';

interface TestCaseWithExpansion extends TestCase {
  expansion: number;
}

export const testCases: TestCaseWithExpansion[] = [
  {
    expansion: 10,
    input: `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`,
    part1Output: 374,
    part2Output: 1030,
  },
  {
    expansion: 100,
    input: `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`,
    part1Output: 374,
    part2Output: 8410,
  },
];
